# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  dockerId: 'sebagomez'

steps:
- script: dotnet build --configuration $(buildConfiguration) src/AngularWebStorageExplorer/AngularWebStorageExplorer.csproj
  displayName: 'dotnet build'
- script: dotnet publish -o ../../Docker/root --configuration $(buildConfiguration) --no-build src/AngularWebStorageExplorer/AngularWebStorageExplorer.csproj
  displayName: 'dotnet publish'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.SourcesDirectory)/Docker' 
    artifactName: 'deploy' 